---
title: "Data Tidying"
author: "Jaedon D. Swanson"
format: html
execute:
  echo: true
  warning: false
  message: false
---
# Packages
- The following packages are necessary to run this code without errors
```{r}
library(tidyverse)
library(ggpmisc)
library(readxl)
library(janitor)
```
## Phosphorus
```{r}
phosphorus <- list.files(path = "~/Desktop/School/MS/Research/Phosphorus/Concentrations",
 pattern = "\\.csv$",
 full.names = TRUE) %>%
 lapply(read_csv) %>%
 bind_rows %>%
  rename(sample_id = Sample) %>%
  rename(phosphorus = Concentration) %>%
  rename(replication = Replication) %>%
  filter(!str_detect(sample_id, "Low STD")) %>%
  select(sample_id, replication, phosphorus) %>%
  mutate(phosphorus = if_else(phosphorus <= 0, NA_real_, phosphorus)) %>%
  mutate(date = str_extract(sample_id, "\\d{8}"))%>%
  mutate(event = case_when(
    str_detect(sample_id, "06212026") ~ "Storm",
    str_detect(sample_id, "07312026") ~ "Storm",
    str_detect(sample_id, "08052026") ~ "Storm",
    TRUE ~ "Base"
    )) %>%
  mutate(type = case_when(
    str_detect(sample_id, "gcp") ~ "Stream", # gcp = stream
    str_detect(sample_id, "elm") ~ "Stream", # elm = stream
    TRUE ~ "Wetland" # not gcp or elm = wetland
    )) %>%
  mutate(site = str_extract(sample_id, "^[^_]+")) %>% # cleaning up sample_id
  filter(!is.na(site)) %>% # removing samples with no site 
  mutate(site = case_match(site,
    "elm-bridge" ~ "Elmwood Downstream",
    "elm-school" ~ "Elmwood Upstream",
    "gcp" ~ "Glacier Creek Preserve",
    "adams-in" ~ "Adams Park Inflow",
    "adams-mid-up" ~ "Adams Park Middle (Upstream)",
    "adams-mid" ~ "Adams Park Middle (Upstream)",
    "adams-mid-down" ~ "Adams Park Middle (Downstream)",
    "adams-out" ~ "Adams Park Outflow",
    "heron-map" ~ "Heron Haven Maple Inflow",
    "her-map" ~ "Heron Haven Maple Inflow",
    "her-resi" ~ "Heron Haven Residential Inflow",
    "her-out" ~ "Heron Haven Outflow",
    "heron-resi" ~ "Heron Haven Residential Inflow",
    "heron-out" ~ "Heron Haven Outflow",
    .default = site))
```
# Data Export
```{r}
#### Saving created CSV files ####
write.csv(phosphorus, "~/Desktop/School/MS/Research/Thesis/Data/phosphorus.csv", row.names = FALSE)
```